server:
  port: 8081
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      uri: "mongodb+srv://mariiamarchenko:PKTnoGYF66RnnNCg@planner.ff7nfot.mongodb.net/"
      database: "test"

secret: planner-very!secret-key(not-weak-at-all)
